// Lucide-react icon re-exports + legacy I.* compatibility object
import {
  Map, Package, Truck, Users, BarChart2, LayoutGrid, Bell, Search, Plus, Filter,
  MoreHorizontal, ChevronRight, ChevronLeft, Check, Phone, MapPin, Settings,
  LogOut, Eye, User, Banknote, TrendingUp, TrendingDown, Star, Download,
  RefreshCw, Car, Clock, Globe, Sun, Moon, Lock, X, AlertCircle, Navigation,
  WifiOff,
} from 'lucide-react'

// Legacy I object so existing pages work without changes
export const I = {
  map:      Map,
  package:  Package,
  truck:    Truck,
  users:    Users,
  chart:    BarChart2,
  board:    LayoutGrid,
  bell:     Bell,
  search:   Search,
  plus:     Plus,
  filter:   Filter,
  more:     MoreHorizontal,
  arrowR:   ChevronRight,
  arrowL:   ChevronLeft,
  check:    Check,
  phone:    Phone,
  pin:      MapPin,
  settings: Settings,
  logout:   LogOut,
  eye:      Eye,
  user:     User,
  lock:     Lock,
  cash:     Banknote,
  trend:    TrendingUp,
  trendDn:  TrendingDown,
  star:     Star,
  download: Download,
  refresh:  RefreshCw,
  car:      Car,
  clock:    Clock,
  globe:    Globe,
  sun:      Sun,
  moon:     Moon,
  close:    X,
}
